spring:
  profiles:
    active: env
  aop:
    proxyTargetClass: true
  devtools:
    restart:
     enabled: false
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    naming:
      physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
jasypt:
  encryptor:
    password: BHE9QEPUvh8HFjm2DCXm6j7wS4Fi
    algorithm: PBEWithMD5AndDES
#    saltGeneratorClassname: org.jasypt.salt.StringFixedSaltGenerator
management:
  endpoints:
    web:
    exposure:
      include: health,info,env,metrics
      #include: health,info,env,prometheus,metrics,httptrace,threaddump,heapdump,springmetrics