server:
  port: 7148
spring:
  application:
    name: payroll
  config:
    use-legacy-processing: true
  main:
    allow-bean-definition-overriding: true
  aop:
    proxyTargetClass: true
  devtools:
    restart:
      enabled: false

#  redis:
#    database: 1
#    #host: 10.5.0.103
#    #port: 26379
#    password: redis1
#    timeout: 1s
#    #哨兵模式
#    sentinel:
#      master: mymaster
#      nodes: 10.5.0.103:26379
#    lettuce:
#      pool:
#        #连接池最大连接数（使用负值表示没有限制）
#        max-active: 40
#        #连接池最大空闲连接，默认：8
#        max-idle: 50
#        #连接池最大阻塞等待时间（使用负值表示没有限制）
#        max-wait: 5000
#        #连接池最小空闲连接，默认：0
#        min-idle: 5
#        #eviction线程调度时间间隔
#        time-between-eviction-runs: 1

  redis:
    database: 1
    host: 10.5.0.182
    port: 6380
    password:
    timeout: 1s
    lettuce:
      pool:
        max-active: 8
        max-idle: 50
        max-wait: -1ms
        min-idle: 0

  data:
    mongodb:
      uri: mongodb://fxgjlogs:123456@10.5.0.182:27017/fxgjlogs?maxPoolSize=256&maxIdleTimeMS=60000

  #  #消息队列
  rabbitmq:
    host: 10.5.0.182
    port: 5672
    username: admin
    password: kayak2003
    virtual-host: /
    connection-timeout: 15000ms
    # 消息发送到交换机确认机制,是否确认回调
    publisher-confirms: true
    # 是否返回回调
    publisher-returns: true
    listener:
      simple:
        # none：没有任何的应答会被发送
        # manual：即为手动ack模式，监听者必须通过调用Channel.basicAck()来告知所有的消息
        # auto:自动确认ack,会自动应答.除非MessageListener抛出异常
        acknowledge-mode: manual
        # 指定最小的消费数量
        concurrency: 1
        # 指定最大的消费数量
        max-concurrency: 1
        retry:
          # 是否支持重试
          enabled: true
    template:
      # 默认为false,Server端会自动删除不可达消息
      mandatory: true
payroll:
  #调用inside地址
  inside-url: http://10.5.0.101:30090/rest/
  #产品图片
  img-url: http://10.5.0.101/

  ###签名回执地址
  signPdfPath: /webserver/www/down/emp/sign/
  ###签名回执地址入库需要替换掉的路径
  signReplacePath: /webserver/

  ###报税签约上传身份证图片地址
  signUploadPath: /webserver/www/upload/sign/

encrypt:
  salt: GUPxMCeBWXw3TteCYVikKVXvH5WLiqZg
  passwd: MvEpyqjedb4Hvai3vnFakmYxQsebEVCe84RNcVxw79USzc85channelFPAmbA9NuPxqfGsMh5pPuyzL

#报税服务设置
tax:
  #渠道
  channel: FXGJ
  #signSalt混淆
  signSalt: zxyh7572
  #公钥
  publicKey: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCNotSn72NFXy92LCc09MjZOAlhngjbUGrDcj8y8pTUMy1tM9NvTjWTMc9OU+bN9pnBzS7sFPJ+aSDaC81p6LeetHwovSkZGdxXMogFow3PPvnc+oc/19oeqsrMrB/bDxjF4sWVNgn+RhXjuOmBLn43WS10ZZ7zEV9DwT8WiyZVqQIDAQAB
  #tax 服务地址
  requestUrl: https://sitapi.lgabc.cn/exgateway/lgb
  #证书名称
  certificateName: api-client.p12
  #证书密码
  password: f2xKYRosKEy5W31r

#正向代理
proxy:
  ip: 17.166.221.1
  port: 3128
  schemeName: http

management:
  endpoints:
    web:
      exposure:
        include: ["*"]


# mongodb 日志记录-
logcss:
  sysId: rs-payroll
  activateMongodb: true
  pool-size: 2
  mongodb:
    uri: mongodb://fxgjlogs:123456@10.5.0.182:27017/fxgjlogs
  maxEntitySize: 500
  headerReqId: reqid
  headerLogToken: logtoken
  headerSessionId: jsessionid


merchants:
  merchant:
    # 分组id
    - appid: wx0345ad9614fe9567
      #appsecret
      appsecret: 05f6b8b23b0decd0c6af48e9f59bfdb9
      #分组名称
      name: 辽宁振兴银行
      #接入平台编号  值是唯一 【取 AppPartnerEnum 枚举值】
      merchantCode: NEWUP
      #请求地扯
      url: http://www.baidu.com
      #重定向工资条地址
      #accessUrl: https://wxp.cardpu.com/fx-payroll/#/token?accessToken=tww9WR8f
      accessUrl:  https://sitwxp.cardpu.com/fx-payroll/#/token?accessToken=ACCESSTOKEN
      #rsa 公钥 -> 平台自已
      rsaPublicKey: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCGYHGGPlZvE4DE7ExTBMDNwJlDKXBiQYaprvxGZ+rf7YqJhxO08UnecTHKpPdA0KGe6vMwgT58AN3Cj1WsytIQ6Y2ybiqSwlpjlFQaNb3jiiE4gnSMkMvxxzRaHQ+Y10Qtfil47wqVq2TCKMMWrgSfMNINoTbSEp10FFbhbVrxpQIDAQAB
      #rsa 私钥 -> 平台自已
      rsaPrivateKey: MIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGBAIZgcYY+Vm8TgMTsTFMEwM3AmUMpcGJBhqmu/EZn6t/tiomHE7TxSd5xMcqk90DQoZ7q8zCBPnwA3cKPVazK0hDpjbJuKpLCWmOUVBo1veOKITiCdIyQy/HHNFodD5jXRC1+KXjvCpWrZMIowxauBJ8w0g2hNtISnXQUVuFtWvGlAgMBAAECgYAjwCzz5kngq3Oq8KMtwyn4k7Ey6Sd5PK2zH1cG9EbM5Mni5QkdLsTUZZE1tMYDfH5DZYbl9LzHCQP262OD4UIZz2mhotBzT6UaZPhdMNsHzNojIwQa+syHTBgFMe39AuDyyes+0pG4rAlolPDMuywgb5yIK+1eMvPiW8nXZvg9AQJBAPOInM/ybSt7iqzL0Am9GOsOsvBXAlKxzUvEAdPi7YcFn5pmHTVQeymeDj+qlMYm56lB14UcTakEdwL/5SYLRXUCQQCNQWJAwDDdKcFw6vtH5WoDh4KeDGupLCQ89g1RpLoZtwq0oe46VexC59EfhG1Kz9zTi2YVrfRnc+lH5WpTLgVxAkEAqENOnXrRpQaB5SwY/HGT4uzQA7EKYNqKjvvJi32yQeVHxiUhrzGBN1sGW0Tf8Bz3WQGuCEFrAwmbtQ3bZLLK9QJAXU6yc2lBHebGNCvUfyKJC/nIi1RTDbXt3iL+m06/69qghL9umTRG089DsZkNhNyX11l+vpVhG7FSiL5/pKCC0QJAMHErhJK0pHG1e64bVbMQNhTPBPlt7WwMMkNU7iewNglPAwUzzeTHbf0wAHfHSo2vpz4BKrKRU6F2HxMOyzaTnQ==df723820
      #rsa 公钥 -> 合作平台
      paraRsaPublicKey: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQD8GdTjtQi8lwmboggiKNdsmMJ1ElvvIGV4J43QCRR/KE6uUYn2TdULVvSbc5LDOlGMQT3sf5/eDQXEZLT5hKOB70Lm1+yrKP0wcbmuIxc6u6UDvlOuJSDL9h6zCmHLPfK8QxYElKhKgF35ZbhLpvGWKdmFjxAdIcg6XHGFnSC9twIDAQAB
      #备注说明
      remarks:
         # 请求前端页面： https://wxp.cardpu.com/fx-payroll/#/token?accessToken=tww9WR8f
         # 请求后端接口获取token ：https://sitwx.cardpu.com/merchant/callback?accessToken=tww9WR8f
      #查询 数据权限   【 取 FundLiquidationEnum  枚举值 】
      dataAuths:
        - NEWUP

#设置feign调用超时时间
#ribbon:
#  ReadTimeout: 30000
#  ConnectTimeout: 30000
#  maxAutoRetries: 0

##禁用feign熔断
#feign:
#  hystrix:
#    enabled: false
#  client:
#    config:
#      default:
#        connectTimeout: 20000
#        readTimeout: 20000
#
##熔断超时时间设置
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 120000
#      timeout:
#        enabled: false

feign:
  client:
    config:
      default:
        connectTimeout: 300000
        readTimeout: 120000
        # NONE  BASIC   HEADRES  FULL
        loggerLevel: FULL
  #使用httpclient 连接池
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  # Hystrix支持，如果为true，hystrix库必须在classpath中
  # 开始熔断、超时时间
  hystrix:
    enabled: false