server:
  port: 8080
## dev
spring:
  data:
    mongodb:
      uri: mongodb://fxgjlogs:123456@10.5.0.182:27017/fxgjlogs
  redis:
    database: 2
    host: 10.5.0.182
    port: 6380
    password:
    timeout: 1s
    jedis:
      pool:
        max-active: 8
        max-idle: 50
        max-wait: -1ms
        min-idle: 0
#management:
#  endpoints:
#    web:
#      exposure:
#        include: ["*"]
fxgj:
  datasource:
    jdbc-url: jdbc:mysql://10.5.0.182:3306/kayak_fxgj?useSSL=false&characterEncoding=utf-8&allowMultiQueries=true
    username: kayak_enterprise
    password: WHDev@20160714
    maximum-pool-size: 5
    pool-name: fxgj_db
encrypt:
  salt: GUPxMCeBWXw3TteCYVikKVXvH5WLiqZg
  passwd: MvEpyqjedb4Hvai3vnFakmYxQsebEVCe84RNcVxw79USzc85FPAmbA9NuPxqfGsMh5pPuyzL
payroll:
  # 微信公众号分组id
  id: zo

  inside-url: http://10.5.0.248:8085/rest/
  img-url: https://sitwxp.cardpu.com/
# 过滤不需要验证权限的路径【自定义】
auth:
  #权限准许的路径列表（此列表下访问路径，不验证token）
  permitall:
    #访问路径
    - pattern: /inside/bindWX/**
    - pattern: /inside/rz/**
    - pattern: /roll/checkCar/**

property:
  # 微信公众号分组id
  id: zo