server:
  port: 8080

spring:
  profiles:
    active: env
  aop:
    proxyTargetClass: true
  devtools:
    restart:
      enabled: false
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    naming:
      physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
  redis:
    database: 2
    host: 10.5.0.182
    port: 6380
    password:
    timeout: 1s
    jedis:
      pool:
        max-active: 8
        max-idle: 50
        max-wait: -1ms
        min-idle: 0
#  data:
#    mongodb:
#      uri: mongodb://fxgjlogs:Kayak20181026@localhost:27017/fxgjlogs
fxgj:
  datasource:
    jdbc-url: jdbc:mysql://10.5.0.182:3306/kayak_fxgj?useSSL=false&characterEncoding=utf-8&allowMultiQueries=true
    username: kayak_enterprise
    password: WHDev@20160714
    maximum-pool-size: 5
    pool-name: fxgj_db

payroll:
  #调用inside地址
  inside-url: http://127.0.0.1:7124/rest/
  #产品图片
  img-url: https://sitwxp.cardpu.com/

encrypt:
  salt: GUPxMCeBWXw3TteCYVikKVXvH5WLiqZg
  passwd: MvEpyqjedb4Hvai3vnFakmYxQsebEVCe84RNcVxw79USzc85FPAmbA9NuPxqfGsMh5pPuyzL

management:
  endpoints:
    web:
      exposure:
        include: ["*"]

#logcss:
#  sysId: fxgj
#  activateMongodb: true
#  pool-size: 2
#  mongodb:
#    uri: mongodb://fxgjlogs:Kayak20181026@localhost:27017/fxgjlogs