server:
  port: 8080
## dev
spring:
  data:
    mongodb:
      uri: mongodb://fxgjlogs:123456@10.5.0.182:27017/fxgjlogs
  redis:
    database: 2
    host: 10.5.0.182
    port: 6380
    password:
    timeout: 1s
    jedis:
      pool:
        max-active: 8
        max-idle: 50
        max-wait: -1ms
        min-idle: 0
#management:
#  endpoints:
#    web:
#      exposure:
#        include: ["*"]