server:
  port: 8080

spring:
  aop:
    proxyTargetClass: true
  devtools:
    restart:
      enabled: false
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    naming:
      physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
  redis:
    database: 2
    host: 10.5.0.182
    port: 6380
    password:
    timeout: 1s
    jedis:
      pool:
        max-active: 8
        max-idle: 50
        max-wait: -1ms
        min-idle: 0
  data:
    mongodb:
      uri: mongodb://fxgjlogs:123456@10.5.0.182:27017/fxgjlogs
fxgj:
  datasource:
    jdbc-url: jdbc:mysql://10.5.0.182:3306/kayak_fxgj?useSSL=false&characterEncoding=utf-8&allowMultiQueries=true
    username: kayak_enterprise
    password: WHDev@20160714
    maximum-pool-size: 5
    pool-name: fxgj_db

payroll:
  #调用inside地址
  inside-url: http://127.0.0.1:7124/rest/
  #产品图片
  img-url: https://sitwxp.cardpu.com/

encrypt:
  salt: GUPxMCeBWXw3TteCYVikKVXvH5WLiqZg
  passwd: MvEpyqjedb4Hvai3vnFakmYxQsebEVCe84RNcVxw79USzc85FPAmbA9NuPxqfGsMh5pPuyzL

management:
  endpoints:
    web:
      exposure:
        include: ["*"]


# mongodb 日志记录
logcss:
  sysId: rs-payroll
  activateMongodb: true
  pool-size: 2
  mongodb:
    uri: mongodb://fxgjlogs:123456@10.5.0.182:27017/fxgjlogs
  maxEntitySize: 500
  headerReqId: reqid
  headerLogToken: logtoken
  headerSessionId: jsessionid

merchants:
  merchant:
    # 分组id
    - appid: wx0345ad9614fe9567
      #appsecret
      appsecret: 05f6b8b23b0decd0c6af48e9f59bfdb9
      #分组名称
      name: 中人联微信对接
      #接入平台编号
      merchantCode: 1
      #请求地扯
      url: http://www.baidu.com
      #重定向工资条地址
      accessUrl: http://localhost:8080/merchant/checkToken
      #rsa 公钥
      rsaPublicKey: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCGYHGGPlZvE4DE7ExTBMDNwJlDKXBiQYaprvxGZ+rf7YqJhxO08UnecTHKpPdA0KGe6vMwgT58AN3Cj1WsytIQ6Y2ybiqSwlpjlFQaNb3jiiE4gnSMkMvxxzRaHQ+Y10Qtfil47wqVq2TCKMMWrgSfMNINoTbSEp10FFbhbVrxpQIDAQAB
      #rsa 私钥
      rsaPrivateKey: MIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGBAIZgcYY+Vm8TgMTsTFMEwM3AmUMpcGJBhqmu/EZn6t/tiomHE7TxSd5xMcqk90DQoZ7q8zCBPnwA3cKPVazK0hDpjbJuKpLCWmOUVBo1veOKITiCdIyQy/HHNFodD5jXRC1+KXjvCpWrZMIowxauBJ8w0g2hNtISnXQUVuFtWvGlAgMBAAECgYAjwCzz5kngq3Oq8KMtwyn4k7Ey6Sd5PK2zH1cG9EbM5Mni5QkdLsTUZZE1tMYDfH5DZYbl9LzHCQP262OD4UIZz2mhotBzT6UaZPhdMNsHzNojIwQa+syHTBgFMe39AuDyyes+0pG4rAlolPDMuywgb5yIK+1eMvPiW8nXZvg9AQJBAPOInM/ybSt7iqzL0Am9GOsOsvBXAlKxzUvEAdPi7YcFn5pmHTVQeymeDj+qlMYm56lB14UcTakEdwL/5SYLRXUCQQCNQWJAwDDdKcFw6vtH5WoDh4KeDGupLCQ89g1RpLoZtwq0oe46VexC59EfhG1Kz9zTi2YVrfRnc+lH5WpTLgVxAkEAqENOnXrRpQaB5SwY/HGT4uzQA7EKYNqKjvvJi32yQeVHxiUhrzGBN1sGW0Tf8Bz3WQGuCEFrAwmbtQ3bZLLK9QJAXU6yc2lBHebGNCvUfyKJC/nIi1RTDbXt3iL+m06/69qghL9umTRG089DsZkNhNyX11l+vpVhG7FSiL5/pKCC0QJAMHErhJK0pHG1e64bVbMQNhTPBPlt7WwMMkNU7iewNglPAwUzzeTHbf0wAHfHSo2vpz4BKrKRU6F2HxMOyzaTnQ==
                     df723820
      #备注说明
      remarks:

